### ISSUE TITLE
Isenção do ISS

### ISSUE THREAD

**Issue by luisrudge** [tapajos/trabalhando_fora#12]
> Dependendo do seu município você ainda pode contar com isenção de ISS. Porém para ter essa isenção é necessário que exista no seu contrato uma cláusula de não verificação em território nacional.

Qual estados ou munícipios tem essa isenção? Emito nota por São Paulo (empresa é Simples) e acho que tenho que pagar :(

**Comment by pedroreys** [comment]
Disclaimer: eu não sou contador :)

Pelo Simples não tem como você solicitar isenção de um imposto específico, já que você não paga os impostos discriminadamente mas o valor agrupado do Simples.

**Comment by luisrudge** [comment]
@pedroreys obrigado pela resposta. Esqueci de fechar essa issue antes, mas minha contadora disse exatamente isso. Valeu!
