### ISSUE TITLE
Sobre a instrução normativa

### ISSUE THREAD

**Issue by ppaulojr** [tapajos/trabalhando_fora#16]
Parece que a frase:

> Pessoa Jurídica: Nesse caso os impostos podem variar bastante de acordo com o tipo da sua empresa e a sua localização. Se a sua empresa for cadastrada no Simples você irá pagar os impostos como se tivesse prestando serviço no Brasil. Caso sua empresa seja de Lucro Presumido você pode usufruir da isenção de PIS e Cofins existente para serviços de exportação de software conforme IN-SRF 247 Art. 46 de 21/11/2012.

Não está de acordo com as regras vigentes. Meu contador insiste em que temos que recolher PIS e Cofins

**Comment by tapajos** [comment]
Já o meu contador diz o oposto do seu. De qualquer maneira vou perguntar novamente para ele.

**Comment by ppaulojr** [comment]
Esta é uma resposta que vale muito $$$ :D

------------------------------
Pedro Paulo Junior



2016-01-21 14:10 GMT-02:00 Marcos Tapajós <notifications@github.com>:

**Comment by tapajos** [comment]
Acabei de enviar esse questionamento ao meu contador.

**Comment by tapajos** [comment]
São isentas da Contribuição para o PIS/Pasep e da Cofins as receitas (IN SRF n º 247, de 21 de novembro de 2002, art. 45):

...

	3 - dos serviços prestados a pessoas físicas ou jurídicas residentes ou domiciliadas no exterior, cujo pagamento represente ingresso de divisas;

fonte: http://www.receita.fazenda.gov.br/PessoaJuridica/PisPasepCofins/IncidImunIsencoes.htm#Isenções

**Comment by ppaulojr** [comment]
É. Você tem razão mesmo. Valeu pela dica!

------------------------------
Pedro Paulo Junior



2016-01-21 14:27 GMT-02:00 Marcos Tapajós <notifications@github.com>:
