### ISSUE TITLE
Taxas para recebimento de remessa

### ISSUE THREAD

**Issue by gustavoschmidt** [tapajos/trabalhando_fora#17]
Boa noite pessoal,
Eu utilizo a Confidence Cambio para receber dinheiro do exterior, mas a taxa deles por operação acabou de subir e gostaria de mudar. Vocês tem alguma outra casa de câmbio ou banco para recomendar?
PS: A Confidence agora cobra R$160,00 reais por operação (além do spread).
Obrigado!

**Comment by carlosbpf** [comment]
Eu fiz um contato com a cotação , uma divisão do banco rendimento. Eles
fazem tudo por telefone e aparte de PJ quem lida é SP. Eles fazem o
procedimento todo pra vc, vc consegue autorizar por telefone e eles fazem
um TED para sua conta. Até onde eu entendi não haviam taxas e eles fazem
apenas o spread. Não pude utilizar pois meu pagador so aceita
transferencias diretas banco a banco.
Espero ter ajudado.

2016-04-13 2:14 GMT-03:00 Gustavo Schmidt <notifications@github.com>:

> Boa noite pessoal,
> Eu utilizo a Confidence Cambio para receber dinheiro do exterior, mas a
> taxa deles por operação acabou de subir e gostaria de mudar. Vocês tem
> alguma outra casa de câmbio ou banco para recomendar?
> PS: A Confidence agora cobra R$160,00 reais por operação (além do spread).
> Obrigado!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tapajos/trabalhando_fora/issues/17>
>



-- 
Carlos Botelho
(61) 8435 - 3513

**Comment by tapajos** [comment]
Eles cobram e se não me engano são 20 dólares para PJ. Estou usando eles já têm uns 2 anos.

**Comment by gustavoschmidt** [comment]
Muito obrigado pelas informações!

**Comment by nuk** [comment]
Alguém já tentou o transferwise.com ?

**Comment by mateusbello** [comment]
Eu já usei, é bom mas acabei mudando para o https://revolut.com/.

**Comment by nuk** [comment]
valeu, vou olhar

**Comment by ericofusco** [comment]
Vou ressuscitar aqui..

Segundo o site da transferwise, pro Brasil ela só aceita transferência de pessoa física para pessoa física. Então mesmo se você recebe como pessoa física no Brasil provavelmente você não vai conseguir usar o transferwise porque a conta no exterior é de empresa.

> Information regarding BRL business payments
> 
> Payments to Brazil can only be personal payments. Both the sender and recipient must be a privately owned account of an individual. The money for a BRL transfer cannot come from a business account,  trust fund, or any type of third party account and it can not be sent to a business in Brazil.

https://transferwise.com/help/article/2002578/latin-american-transfers/brl-transfers

Não sei se o link está desatualizado, mas eu vou dar uma ligada lá pra confirmar.

**Comment by tsuharesu** [comment]
Tenho uma conta PF no Inter e eles não cobram taxa alguma, só o spread. E ele é bem pequeno. Recebo em dólar canadense, e quando ele estava em 2.72 me passaram a 2.70.
Só é um procedimento mais chatinho (confirmar por e-mail, demora alguns dias para eles avisarem que caiu na conta), não tem nada automatizado como no Itaú. Mas pra mim vale mais a pena.

**Comment by tapajos** [comment]
Recentemente mudei de corretora e fui para a B&T. Eles tem um spread de 1.5% em relação ao cambio oficial e mais nada. 

O processo de abertura da minha conta foi finalizado em uma tarde, nunca vi algo tão rápido.

O fechamento é feito via e-mail e (se necessário) a assinatura é digital.

Se alguém se interessar posso passar o meu ponto de contato.
